# Generated by Django 3.2 on 2021-08-06 08:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('EmployeeId', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
