# Generated by Django 3.2 on 2021-08-06 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('electrical', 'ELECTRICAL'), ('hvac', 'HVAC'), ('Cleaning related', 'CLEANING RELATED'), ('others', 'OTHERS')], max_length=50)),
                ('Floor', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)])),
                ('Desk_No', models.CharField(max_length=10)),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('open', 'OPEN'), ('pending', 'PENDING'), ('closed', 'CLOSED')], default='OPEN', max_length=50)),
                ('Admin_comments', models.TextField()),
            ],
        ),
    ]
