# Generated by Django 3.2 on 2021-08-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_App', '0002_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='User',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
